#!/bin/bash




cb="callback(deleteBlog,blog)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser=${user} webapp=${app} a=${cb}	\
table:"blog":"blog.blog":"0":"type":"textarea"	\
table:"blog":"blog.idContact":"0":"value":"0"	\
table:"blog":"blog.idContact":"0":"type":"hidden"	\
table:"blog":"blog.created":"0":"value":"42241"	\
table:"blog":"blog.created":"0":"type":"hidden"	\
table:"blog":"blog.idCompany":"0":"value":"2"	\
table:"blog":"blog.idCompany":"0":"type":"hidden"	\
table:"blog":"blog.idBlog":"0":"value":"10001"	\
table:"blog":"blog.idBlog":"0":"type":"hidden"	\
table:"blog":"blog.idRep":"0":"value":"1"	\
table:"blog":"blog.idRep":"0":"type":"hidden"	\
table:"blog":"blog.blog":"0":"value":"NieuweCompanyBlogContent"	\
> ${dir}/${fn}_new.html 2>&1
