#!/bin/bash




cb="callback(mergeContact,merge)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser=${user} webapp=${app} a=${cb}	\
table:"merge":"import.idContact":"0":"type":"select"	\
table:"merge":"this.idContact":"0":"value":"1002"	\
table:"merge":"this.idContact":"0":"type":"hidden"	\
table:"merge":"import.idContact":"0":"value":"2002"	\
> ${dir}/${fn}_new.html 2>&1
