#!/bin/bash


tools="${HOME}/proAppNest/proAppNestTools/"
dir=${0%\/*} 
fname=${0##*-}
loc=`pwd`
tloc=${loc%\/*} 
account=${tloc##*\/}

printf " $fname $1 "

app="Sales"
user="manager@inspirationalsales.demo.nl"


fn=1100

cb="callback(tasksPage)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser=${user} webapp=${app} a="${cb}"		\
> ${dir}/${fn}_new.html 2>&1

cb="callback(tasksPage)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser="teamleider@inspirationalsales.demo.nl" webapp=${app} a="${cb}"		\
> ${dir}/${fn}_new.html 2>&1


cb="callback(tasksPage)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser="agent@inspirationalsales.demo.nl" webapp=${app} a="${cb}"		\
> ${dir}/${fn}_new.html 2>&1

exit
fn=1090
cb="callback(tasksPage)"
let fn+=1
printf "."
php ${tools}/do.php ${account}/index loginUser="edward@inspirationalsales.nl" webapp=${app} a="${cb}"		\
"table[inPageSelectaccountSelect][idAccount][0][value]:4"				\
"table[inPageSelectaccountSelect][idAccount][0][type]:select"			\
"table[inPageSelectaccountSelect][haveSelect][0][value]:1"				\
"table[inPageSelectaccountSelect][haveSelect][0][type]:hidden"			\
> ${dir}/${fn}_new.html 2>&1
exit
